// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class Language
{
    public int Id { get; set; }

    public string LocalName { get; set; }

    public string CultureName { get; set; }

    public string FriendlyName { get; set; }

    public bool Active { get; set; }

    public int DisplayOrder { get; set; }

    public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; set; } = new List<MetaTagLocalized>();

    public virtual ICollection<ProductLocalized> ProductLocalizeds { get; set; } = new List<ProductLocalized>();
}