// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class MetaTag
{
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    public string PageName { get; set; }

    public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; set; } = new List<MetaTagLocalized>();
}