// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class ProductLocalized
{
    public int ProductId { get; set; }

    public int LanguageId { get; set; }

    public string Name { get; set; }

    public virtual Language Language { get; set; }

    public virtual Product Product { get; set; }
}